version: '2'
services:
  organicpromotickets-app:
    image: organicpromotickets
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://organicpromotickets-postgresql:5432/OrganicPromoTickets
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  organicpromotickets-postgresql:
    extends:
      file: postgresql.yml
      service: organicpromotickets-postgresql
