version: '2'
services:
  organicpromotickets-postgresql:
    image: postgres:12.3
    volumes:
      - ~/volumes/jhipster/OrganicPromoTickets/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=OrganicPromoTickets
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
